### ISSUE TITLE
Sample table format/config file specification 

### ISSUE THREAD

**Issue by taylorreiter** [SilasK/amplicon-seq-dada2#1]
Hi @SilasK! I see that the snakefile reads in a sample table referenced in the config file (https://github.com/SilasK/amplicon-seq-dada2/blob/master/Snakefile#L5):

```
SampleTable = pd.read_table(config['sampletable'],index_col=0)
```

but I can't find an example of a sample table, and I don't see the sample table referenced in the config file. Would you be willing to provide an example?

**Comment by SilasK** [comment]
Sorry, I was on holidays. I try to answer your questions asap.

**Comment by SilasK** [comment]
@taylorreiter I added some more infos, a conda env and a  test script. This should help you to use the pipeline. 

 Somethimes there are RSV that are much shorter than the expected length. Therefore I added a step where I filter the amplicon for length variation. I don't know if this interferes with an ITS. But you can set a very high number in the config file.

**Comment by taylorreiter** [comment]
Thank you!!
