### ISSUE TITLE
dada2.smk threads issue

### ISSUE THREAD

**Issue by colindaven** [SilasK/amplicon-seq-dada2#8]
Thanks for the rapid changes. I am not sure why dada2 has an issue. 

My config.yaml is unchanged in the threads section:

threads: 4

```
snakemake
KeyError in line 28 of /ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/rules/dada2.smk:
'threads'
  File "/ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/Snakefile", line 97, in <module>
  File "/ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/rules/dada2.smk", line 28, in <module>

(dada2_env) rcug@hpc-rc03:/ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2$ snakemake --cores 10
KeyError in line 28 of /ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/rules/dada2.smk:
'threads'
  File "/ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/Snakefile", line 97, in <module>
  File "/ngsssd1/rcug/public_metagenome/soil_16S/16S-dada2/rules/dada2.smk", line 28, in <module>

```

**Comment by SilasK** [comment]
I think you need to supply the path to the config file. see 87fc195

**Comment by colindaven** [comment]
Thanks, this works for me now.

` snakemake --configfile config.yaml --cores 10
`

Building DAG of jobs...

**Comment by SilasK** [comment]
Great! Thank you for helping me to iron out this bugs.

Keep in mind that the pipeline uses dada2=1.14.
I’m not sure if there are any important new features in dada2 that aren’t implemented in this pipeline.

In theory you could just update the dada2 version and see if it works without problems.

Also have a look at https://github.com/SilasK/CoDaSeq

**Comment by colindaven** [comment]
Ok, thanks for the hint. I'll test the pipeline with more data and start getting used to this. I've been a lot more into metagenomics rather than 16S profiling to date, which we also have written software for. I'm skeptical whether either are good enough for the clinic, but see much more potential in metagenomics, especially in the ability to query the reliability of results. cheers.

**Comment by SilasK** [comment]
Ah, I didn't send you the link to the pipeline. Here is my snakmake for aldex https://github.com/SilasK/microbiome-analysis

I work also much more with metagenomes, but I think the tools developed by g. Gloor, like aldex are also easily adabted to metagenomics. 

You are using metagenomics and 16S in the clinics, what for?
what do you mean by ?
> query the reliability of results.

**Comment by colindaven** [comment]
Ok, thanks. re metagenomics, that's good to hear. Our pipeline is here: https://github.com/MHH-RCUG/Wochenende

By reliability of results, I mean we can map many reads to each and related genomes  and plot the results, and also check the mapping quality, to assess whether the genome is really there, or is just a related species with partial genome coverage (false positive), or is low level contamination - etc etc. Even with those points, it is still a tricky subject.

We're mostly working on airway metagenomics of various diseases.
