### ISSUE TITLE
EOL while scanning string literal

### ISSUE THREAD

**Issue by mw55309** [SilasK/amplicon-seq-dada2#9]
Hi

I created the conda env and activated it, then tried a dry run:

```
snakemake --configfile config.yaml -n
```

This produces an error:

```
SyntaxError in line 10 of 16S-dada2/Snakefile:
EOL while scanning string literal
```

Not sure what's going on, is this a Python version?

```
$ which python
/home/ubuntu/miniconda3/envs/dada2_env/bin/python
$ python --version
Python 3.6.13
```

**Comment by SilasK** [comment]
Thank you for noticing. It's fixed on the master branch. you can simply run `git pull` I think
